### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by htfy96** [sjtug/lug#38]
Captured by our monitor system.

```
goroutine 1 [running]:
runtime.throw(0x958490, 0x21)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc4200578c8 sp=0xc4200578a8 pc=0x42c7a5
runtime.mapaccess1_faststr(0x8c3060, 0xc4208a4690, 0x947188, 0x5, 0x891680)
	/usr/local/go/src/runtime/hashmap_fast.go:217 +0x43a fp=0xc420057920 sp=0xc4200578c8 pc=0x40d2ea
github.com/sjtug/lug/vendor/github.com/sirupsen/logrus.(*TextFormatter).Format(0xc4200f0220, 0xc4202a6a80, 0xc4202a6a80, 0xc420057ae8, 0x6c8d84, 0xc4201d00c0, 0xc4202a6a80)
	/go/src/github.com/sjtug/lug/vendor/github.com/sirupsen/logrus/text_formatter.go:91 +0x454 fp=0xc420057a80 sp=0xc420057920 pc=0x6caee4
github.com/sjtug/lug/vendor/github.com/sirupsen/logrus.(*Entry).Reader(0xc4202a6a80, 0x341994b1b04, 0xc4202a6a80, 0x0)
	/go/src/github.com/sjtug/lug/vendor/github.com/sirupsen/logrus/entry.go:44 +0x40 fp=0xc420057af8 sp=0xc420057a80 pc=0x6c6890
github.com/sjtug/lug/vendor/github.com/sirupsen/logrus.Entry.log(0xc4200661c0, 0xc4208a4690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4, 0xc4202920a0, ...)
	/go/src/github.com/sjtug/lug/vendor/github.com/sirupsen/logrus/entry.go:94 +0x117 fp=0xc420057bb8 sp=0xc420057af8 pc=0x6c7017
github.com/sjtug/lug/vendor/github.com/sirupsen/logrus.(*Entry).Info(0xc4202a6a40, 0xc420057d98, 0x1, 0x1)
	/go/src/github.com/sjtug/lug/vendor/github.com/sirupsen/logrus/entry.go:129 +0x9a fp=0xc420057c20 sp=0xc420057bb8 pc=0x6c754a
github.com/sjtug/lug/manager.(*Manager).Run(0xc42019ca80)
	/go/src/github.com/sjtug/lug/manager/manager.go:105 +0xf55 fp=0xc420057f20 sp=0xc420057c20 pc=0x83c885
main.main()
	/go/src/github.com/sjtug/lug/main.go:110 +0x104 fp=0xc420057f80 sp=0xc420057f20 pc=0x83e5c4
runtime.main()
	/usr/local/go/src/runtime/proc.go:195 +0x226 fp=0xc420057fe0 sp=0xc420057f80 pc=0x42de96
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420057fe8 sp=0xc420057fe0 pc=0x45a611
```

**Comment by htfy96** [comment]
Refs: 

https://github.com/sirupsen/logrus/issues/468
https://github.com/sirupsen/logrus/issues/364

**Comment by htfy96** [comment]
After some research, I found that `Fire` of logrustash will keep an `entry *logrus.Entry` and write `entry.Data` at https://github.com/cheshir/logrustash/blob/master/logstash.go#L221 . Unfortunately, at the same time this `entry` may also be read by textFormatter at logrus.

This has been fixed by logrus upstream at https://github.com/sirupsen/logrus/commit/be569094e9c87b6de4fa8909e1e7db1603702f9f#diff-32f22e4789509e4288e8ee93f532fbd0
